name: 'commit jacoco total to some file (readme.md?)'
description: 'commits jacoco total coverage badge to a speficied file (or default readme.md)'
author: 'silviuilie'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  readmeFileName:
    description: 'name of the file that contains the (previous) coverage badge - to be replaced by the new one'
    required: false
    default: 'readme.md'
  jacocoFileName:
    description: 'name of the jacoco xml file - defaults to target/site/jacoco/jacoco.xml'
    required: false
    default: 'target/site/jacoco/jacoco.xml'
  type:
    description: 'flavour of the badge; svg, text or img.shields.io/badge'
    required: false
    default: 'svg'
  
runs:
  using: node20
  main: dist/index.js
