name: 'commit jacoco total to some file (readme.md?)'
description: 'commits jacoco total coverage to a speficied file (or default readme.md)'
author: 'poor man`s tools'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
